services:
  gen:
    container_name: sploon-bin-patch-gen
    build: .
    volumes:
      - ./config.toml:/app/config.toml
      - ./work:/app/run
      - /tmp/bpg:/tmp/bin-patch-gen
    mem_limit: 2G
  tests:
    container_name: sploon-bin-patch-gen-tests
    build:
      dockerfile: Dockerfile.test
    volumes:
      - ./config.toml:/app/config.toml
      - ./work:/app/run
      - /tmp/bpg:/tmp/bin-patch-gen
    mem_limit: 2G
